# NOTE: update this with your service name
service: uplan-app-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  # 'iamRoleStatements' defines the permission policy for the Lambda
  # function.
  # In this case Lambda functions are granted with permissions to
  # access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:985930350642:table/semesters"
      # Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
      # To load environment variables externally
      # rename env.example to env.yml and uncomment
      # the following line. Also, make sure to not
      # commit your env.yml.
      #
      #environment: ${file(env.yml):${self:provider.stage}}

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

functions:
  createSemester:
    handler: createSemester.main
    events:
      - http:
          path: semesters
          method: post
          cors: true
          authorizer: aws_iam
  getSemester:
    handler: getSemester.main
    events:
      - http:
          path: semesters/{id}
          method: get
          cors: true
          authorizer: aws_iam
  getSemesterList:
    handler: getSemesterList.main
    events:
      - http:
          path: semesters
          method: get
          cors: true
          authorizer: aws_iam
  updateSemester:
    handler: updateSemester.main
    events:
      - http:
          path: semesters/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteSemester:
    handler: deleteSemester.main
    events:
      - http:
          path: semesters/{id}
          method: delete
          cors: true
          authorizer: aws_iam
