export const ModalModes = {
  NEW_SEMESTER: 'NEW_SEMESTER',
  UPDATE_SEMESTER: 'UPDATE_SEMESTER',
  NEW_MODULE: 'NEW_MODULE',
  UPDATE_MODULE: 'UPDATE_NEW_MODULE',
  NEW_TAG: 'NEW_TAG',
  UPDATE_TAG: 'UPDATE_TAG',
};
